### ISSUE TITLE
pyrax - out of date

### ISSUE THREAD

**Issue by crazzyfool** [rackspace/pyrax#618]
Hi,

Pyrax is out-of-date and insists on pulling in the old python-novaclient-2.27.0 package!  Can this not be updated to pull in python-novaclient-6.0.0?

Currently it is not possible to install pyrax **_and_** supernova on the same device!  Supernova removes 2.27.0:

```
...
  Found existing installation: python-novaclient 2.27.0
    Uninstalling python-novaclient-2.27.0:
      Successfully uninstalled python-novaclient-2.27.0
Successfully installed configobj-5.0.6 debtcollector-1.8.0 keystoneauth1-2.12.1 monotonic-1.2 netifaces-0.10.5 oslo.i18n-3.9.0 oslo.serialization-2.13.0 oslo.utils-3.16.0 pbr-1.10.0 positional-1.1.1 pyparsing-2.1.9 python-novaclient-6.0.0 pytz-2016.7 requests-2.11.1 six-1.10.0 stevedore-1.17.1
```

**Comment by sivel** [comment]
Pyrax has been deprecated in favor of, the currently in development, rackspacesdk.  As such we are no longer developing pyrax and have decided to freeze its dependencies to known working versions.

https://pypi.python.org/pypi/rackspacesdk

rackspacesdk is not yet a full replacement for pyrax, and should you need to utilize pyrax it is recommended that you install pyrax inside of a python virtualenv to handle dependency versions.

**Comment by briancurtin** [comment]
The support for Nova/Cloud Servers in openstacksdk/rackspacesdk currently includes support for the following resources, which make up a pretty good portion of them. It's fairly easy to add the rest so if there's something you need now it can be added, otherwise we'll eventually get through everything:

- metadata
- server ip
- server interface
- server group
- image
- hypervisor
- extension
- availability zone
- keypair
- limits
- flavor
- service
- server
